train:
  dataset_path: "./../Datasets/v1"
  trainable_layers: 1 # 0 all frozen, 5 all non-frozen
  epochs: 3
  batch_size: 4
  model_name: "my_test"

transformations: # put the probability to incorporate it
  horizontal_flip: 0.5

error_analysis:
  model_path: "./../m_v3_50e.pth"
  dataset_path: "./../Datasets/v1"
  apply_to_train: True
  apply_to_valid: True
  apply_to_test: True
  folder_name: 'Analysis_mv3_d1'