train:
  dataset_path: "./../Datasets/v3"
  trainable_layers: 5 # 0 all frozen, 5 all non-frozen
  epochs: 50
  batch_size: 8
  model_name: "my_name"

error_analysis:
  model_path: "./../m_v3_50e.pth"
  dataset_path: "./../Datasets/v1"
  apply_to_train: True
  apply_to_valid: True
  apply_to_test: True
  folder_name: 'Analysis_mv3_d1'