train:
  dataset_path: "./../Datasets/v4"
  trainable_layers: 5 # 0 all frozen, 5 all non-frozen
  epochs: 30
  batch_size: 4
  model_name: "retinanet"
  save_model_as: "retina_v4_30e_fullAug"
  learning_rate: 5e-3
  use_wandb: True
  wandb_entity: aayushmaan

# put the probability to incorporate each transformation.
# Only 1 transformation is going to be picked (at random) for any example
# if there are multiple, the numbers are going to be 
# weights.
transformations: 
  brightness: 1
  contrast: 1
  defocus: 1
  equalize: 1
  horizontal_flip: 1
  hue_saturation_value: 1
  sharpen: 1
  solarize: 1
  rgbshift: 1

error_analysis:
  model_path: "./../retina_v4_30e_fullAug.pth"
  model_name: "retinanet"
  dataset_path: "./../Datasets/v4"
  apply_to_train: True
  apply_to_valid: True
  apply_to_test: True
  folder_name: 'Analysis_Retina'
  transformation: True # True if to use it in training dataloader