train:
  dataset_path: "./../Datasets/v1"
  trainable_layers: 1 # 0 all frozen, 5 all non-frozen
  epochs: 1
  batch_size: 2
  model_name: "retinanet"
  save_model_as: "testing_delete" # dont include extension in this value

# put the probability to incorporate each transformation.
# Only 1 transformation is going to be picked (at random) for any example
# if there are multiple, the numbers are going to be 
# weights.
transformations:
  one_of_probability: 0.5 # prob of using one of the transformations below
  brightness_contrast: 1
  defocus: 1
  equalize: 1
  horizontal_flip: 1
  hue_saturation_value: 1
  sharpen: 1
  solarize: 1
  rgbshift: 1

error_analysis:
  model_path: "./../m_v4_30e_9augs_Adam.pth"
  model_name: "fasterrcnn" # 'fasterrcnn' or 'retinanet'
  dataset_path: "./../Datasets/v6"
  apply_to_train: False
  apply_to_valid: True
  apply_to_test: True
  folder_name: './../FasterRCNN'
  transformation: False # True if to use it in training dataloader
  compute_metrics: True