train:
  dataset_path: "./../Datasets/v1"
  trainable_layers: 1 # 0 all frozen, 5 all non-frozen
  epochs: 2
  batch_size: 4
  model_name: "retinanet"
  save_model_as: "testing"

# put the probability to incorporate each transformation.
# Only 1 transformation is going to be picked (at random) for any example
# if there are multiple, the numbers are going to be 
# weights.
transformations: 
  brightness: 1
  contrast: 1
  defocus: 1
  equalize: 1
  horizontal_flip: 1
  hue_saturation_value: 1
  sharpen: 1
  solarize: 1
  rgbshift: 1

error_analysis:
  model_path: "./../m_v4_30e_HF50.pth"
  dataset_path: "./../Datasets/v1"
  apply_to_train: True
  apply_to_valid: False
  apply_to_test: False
  folder_name: 'Analysis_test'
  transformation: True # True if to use it in training dataloader