train:
  dataset_path: "./NBA-Player-Detector-1"
  trainable_layers: 3 # 0 all frozen, 5 all non-frozen
  epochs: 3
  batch_size: 2
  model_name: "retinanet" # 'fasterrcnn' or 'retinanet'
  save_model_as: "testing_model" # dont include extension in this value

# put the probability to incorporate each transformation.
# Only 1 transformation is going to be picked (at random) for any example
# if there are multiple, the numbers are going to be 
# weights.
transformations:
  one_of_probability: 1 # prob of using one of the transformations below
  brightness_contrast: 1
  defocus: 1
  equalize: 1
  horizontal_flip: 1
  hue_saturation_value: 1
  sharpen: 1
  solarize: 1
  rgbshift: 1

error_analysis:
  model_path: "./testing_model.pth"
  model_name: "retinanet" # 'fasterrcnn' or 'retinanet'
  dataset_path: "./../Datasets/v11"
  apply_to_train: False
  apply_to_valid: False
  apply_to_test: True
  folder_name: './Analysis' # will make a new folder if not existant
  transformation: False # True if to use it in training dataloader
  compute_metrics: True